In [28]:
# Import modules
import pandas as pd
import numpy as np
from pprint import pprint

# Read csv file
csvfile = pd.read_csv('Resources/Airbnb_Open_Data.csv')
csvfile

C:\Users\nbart.DESKTOP-3OF7M8N\AppData\Local\Temp\ipykernel_2948\1812108956.py:7: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  csvfile = pd.read_csv('Resources/Airbnb_Open_Data.csv')

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN

In [29]:
airbnb_df = pd.DataFrame(csvfile, columns=['id', 'neighbourhood group', 'neighbourhood', 'lat', 'long',
                    'service fee', 'price', 'room type', 'cancellation_policy', 'minimum nights', 'Construction year', 'number of reviews', 'reviews per month',
                    'review rate number', 'calculated host listings count', 'availability 365'])
airbnb_df

,id,neighbourhood group,neighbourhood,lat,long,service fee,price,room type,cancellation_policy,minimum nights,Construction year,number of reviews,reviews per month,review rate number,calculated host listings count,availability 365
0,1001254,Brooklyn,Kensington,40.64749,-73.97237,$193,$966,Private room,strict,10.0,2020.0,9.0,0.21,4.0,6.0,286.0
1,1002102,Manhattan,Midtown,40.75362,-73.98377,$28,$142,Entire home/apt,moderate,30.0,2007.0,45.0,0.38,4.0,2.0,228.0
2,1002403,Manhattan,Harlem,40.80902,-73.94190,$124,$620,Private room,flexible,3.0,2005.0,0.0,NaN,5.0,1.0,352.0
3,1002755,Brooklyn,Clinton Hill,40.68514,-73.95976,$74,$368,Entire home/apt,moderate,30.0,2005.0,270.0,4.64,4.0,1.0,322.0
4,1003689,Manhattan,East Harlem,40.79851,-73.94399,$41,$204,Entire home/apt,moderate,10.0,2009.0,9.0,0.10,3.0,1.0,289.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Brooklyn,Williamsburg,40.70862,-73.94651,$169,$844,Private room,flexible,1.0,2003.0,0.0,NaN,3.0,1.0,227.0
102595,6092990,Manhattan,Morningside Heights,40.80460,-73.96545,$167,$837,Private room,moderate,1.0,2016.0,1.0,0.02,2.0,2.0,395.0
102596,6093542,Brooklyn,Park Slope,40.67505,-73.98045,$198,$988,Private room,moderate,3.0,2009.0,0.0,NaN,5.0,1.0,342.0
102597,6094094,Queens,Long Island City,40.74989,-73.93777,$109,$546,Entire home/apt,strict,2.0,2015.0,5.0,0.10,3.0,1.0,386.0
102598,6094647,Manhattan,Upper West Side,40.76807,-73.98342,$206,"$1,032",Entire home/apt,flexible,1.0,2010.0,0.0,NaN,3.0,1.0,69.0

In [38]:
# airbnb_df[airbnb_df.drop_duplicates(keep='first', inplace=False, ignore_index=False)]

clean_df = airbnb_df.drop_duplicates(keep='first')
clean_df

,id,neighbourhood group,neighbourhood,lat,long,service fee,price,room type,cancellation_policy,minimum nights,Construction year,number of reviews,reviews per month,review rate number,calculated host listings count,availability 365
0,1001254,Brooklyn,Kensington,40.64749,-73.97237,$193,$966,Private room,strict,10.0,2020.0,9.0,0.21,4.0,6.0,286.0
1,1002102,Manhattan,Midtown,40.75362,-73.98377,$28,$142,Entire home/apt,moderate,30.0,2007.0,45.0,0.38,4.0,2.0,228.0
2,1002403,Manhattan,Harlem,40.80902,-73.94190,$124,$620,Private room,flexible,3.0,2005.0,0.0,NaN,5.0,1.0,352.0
3,1002755,Brooklyn,Clinton Hill,40.68514,-73.95976,$74,$368,Entire home/apt,moderate,30.0,2005.0,270.0,4.64,4.0,1.0,322.0
4,1003689,Manhattan,East Harlem,40.79851,-73.94399,$41,$204,Entire home/apt,moderate,10.0,2009.0,9.0,0.10,3.0,1.0,289.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102053,57365208,Brooklyn,Flatbush,40.64945,-73.96108,NaN,$696,Private room,moderate,7.0,NaN,12.0,0.44,5.0,1.0,0.0
102054,57365760,Brooklyn,Bushwick,40.69872,-73.92718,NaN,$909,Private room,flexible,1.0,NaN,19.0,0.72,3.0,2.0,0.0
102055,57366313,Brooklyn,Bedford-Stuyvesant,40.67810,-73.90822,NaN,$387,Entire home/apt,moderate,2.0,NaN,50.0,3.12,4.0,2.0,235.0
102056,57366865,Manhattan,Harlem,40.81248,-73.94317,NaN,$848,Private room,strict,2.0,NaN,0.0,NaN,1.0,1.0,0.0
102057,57367417,Manhattan,Harlem,40.81315,-73.94747,NaN,"$1,128",Entire home/apt,flexible,4.0,2011.0,22.0,0.85,4.0,1.0,238.0